In [1]:
# CSE 
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)     # X = (hours sleeping, hours studying)
y = np.array(([92], [86], [89]), dtype=float)           # y = score on test

# scale units
X = X/np.amax(X, axis=0)        # maximum of X array
y = y/100                       # max test score is 100

class Neural_Network(object):
    def __init__(self):
                            # Parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
                             # Weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)        # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)       # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
                             #forward propagation through our network
        self.z = np.dot(X, self.W1)               # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)            # activation function
        self.z3 = np.dot(self.z2, self.W2)        # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)                 # final activation function
        return o 

    def sigmoid(self, s):
        return 1/(1+np.exp(-s))     # activation function 

    def sigmoidPrime(self, s):
        return s * (1 - s)          # derivative of sigmoid
    
    def backward(self, X, y, o):
                                    # backward propgate through the network
        self.o_error = y - o        # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to 
        self.z2_error = self.o_delta.dot(self.W2.T)    # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error
        self.W1 += X.T.dot(self.z2_delta)       # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta)  # adjusting second set (hidden --> output) weights

    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

NN = Neural_Network()
print ("\nInput: \n" + str(X))
print ("\nActual Output: \n" + str(y)) 
print ("\nPredicted Output: \n" + str(NN.forward(X)))
print ("\nLoss: \n" + str(np.mean(np.square(y - NN.forward(X)))))     # mean sum squared loss)
NN.train(X, y)


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.46794265]
 [0.45452134]
 [0.43953597]]

Loss: 
0.1905622100435118


In [2]:
# AIML

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

sales = pd.read_csv("Advertising.csv")

X = sales[["TV", "Radio", "Newspaper"]]
y = sales["Sales"]

# Standardizes features
X = X.apply(lambda x: (x - X.mean()) / X.std(), axis = 1)

# Scaling target variable

y_scaler = MinMaxScaler()
y_transformed = y_scaler.fit_transform(np.reshape(y, (-1,1)))

def sigmoid(x):
    """
    Returns sigmoid value for the input parameter
    """
    
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    """
    Returns derivative of sigmoid function
    """
    
    return x * (1 - x)


# Count of units in the input layer; The count is equal to the number of features in data set
input_layer_units = X.shape[1]

# number of units at output layer; It is one for target being a continous variable
output_layer_units = 1


# Hyperparameters initialization

# Number of times training data will be used for model training
epoch = 5000

learning_rate = 0.1

# Count of units in the hidden layer; It was assumed that there will be just one hidden layer
hidden_layer_units = 3


# Weights from input layer nodes to hidden layer nodes
hidden_layer_weights = np.random.uniform(size=(input_layer_units, hidden_layer_units))

# Biases for hidden layer nodes
hidden_layer_biases = np.random.uniform(size=(1, hidden_layer_units))
                                         
# Weights from hidden layer nodes to output layer nodes
output_layer_weights = np.random.uniform(size=(hidden_layer_units,output_layer_units))

# Biases for output layer nodes
output_layer_biases=np.random.uniform(size=(1,output_layer_units))


for i in range(epoch):

    #Forward Propogation
    hidden_layer_nets = np.dot(X, hidden_layer_weights)
    hidden_layer_nets = hidden_layer_nets + hidden_layer_biases
    hidden_layer_outputs = sigmoid(hidden_layer_nets)
    
    output_layer_nets = np.dot(hidden_layer_outputs, output_layer_weights)
    output_layer_nets = output_layer_nets + output_layer_biases
    output = sigmoid(output_layer_nets)

    #Backpropagation
    output_error = y_transformed - output
    output_gradients = sigmoid_derivative(output)
    output_delta = output_error * output_gradients
    hidden_layer_error = output_delta.dot(output_layer_weights.T)

    # Calculation of hidden layer weights' contribution to error
    hidden_layer_gradients = sigmoid_derivative(hidden_layer_outputs)
    hidden_layer_delta = hidden_layer_error * hidden_layer_gradients

    # Weights updates for both output and hidden layer units
    output_layer_weights += learning_rate * hidden_layer_outputs.T.dot(output_delta)
    hidden_layer_weights += learning_rate * X.T.dot(hidden_layer_delta)

# Transforms data back from scaled ones
predictions = y_scaler.inverse_transform(output)


# Shows the predicted sales against actual sale for all data points
pd.DataFrame({"Actual Sale": y, "Predicted Sale": predictions.flatten()})

Actual Sale  Predicted Sale
0           22.1       20.496948
1           10.4       10.536427
2            9.3       10.196403
3           18.5       17.254924
4           12.9       11.831302
..           ...             ...
195          7.6        7.369535
196          9.7       10.187097
197         12.8       12.606203
198         25.5       23.733581
199         13.4       14.755203

[200 rows x 2 columns]

In [3]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0)
y = y/100
print(X)

def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

epoch=5000 	
lr=0.1 		
inputlayer_neurons = 2 		
hiddenlayer_neurons = 3 	
output_neurons = 1

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
    hinp1=np.dot(X,wh)
    hinp=hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp= outinp1+ bout
    output = sigmoid(outinp)
    n= 0
    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO* outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

wout += hlayer_act.T.dot(d_output) *lr
wh += X.T.dot(d_hiddenlayer) *lr
n+=1
print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.87378388]
 [0.85341593]
 [0.87406796]]


In [4]:
import numpy as np 

inputNeurons=2 
hiddenlayerNeurons=4 
outputNeurons=2 
iteration=6000

input = np.random.randint(1,5,inputNeurons) 
output = np.array([1.0,0.0]) 
hidden_layer=np.random.rand(1,hiddenlayerNeurons)

hidden_biass=np.random.rand(1,hiddenlayerNeurons) 
output_bias=np.random.rand(1,outputNeurons) 
hidden_weights=np.random.rand(inputNeurons,hiddenlayerNeurons) 
output_weights=np.random.rand(hiddenlayerNeurons,outputNeurons)

def sigmoid (layer):
    return 1/(1 + np.exp(-layer))

def gradient(layer): 
    return layer*(1-layer)

for i in range(iteration):

    hidden_layer=np.dot(input,hidden_weights) 
    hidden_layer=sigmoid(hidden_layer+hidden_biass)

    output_layer=np.dot(hidden_layer,output_weights) 
    output_layer=sigmoid(output_layer+output_bias)

    error = (output-output_layer) 
    gradient_outputLayer=gradient(output_layer)
    error_terms_output=gradient_outputLayer * error 
    error_terms_hidden=gradient(hidden_layer)*np.dot(error_terms_output,output_weights.T)

    gradient_hidden_weights = np.dot(input.reshape(inputNeurons,1),error_terms_hidden.reshape(1,hiddenlayerNeurons))
    gradient_ouput_weights = np.dot(hidden_layer.reshape(hiddenlayerNeurons,1),error_terms_output.reshape(1,outputNeurons))

    hidden_weights = hidden_weights + 0.05*gradient_hidden_weights 
    output_weights = output_weights + 0.05*gradient_ouput_weights 
    if i<50 or i>iteration-50:
        print("**********************") 
        print("iteration:",i,"::::",error) 
        print("###output########",output_layer)

**********************
iteration: 0 :::: [[ 0.04732496 -0.76056057]]
###output######## [[0.95267504 0.76056057]]
**********************
iteration: 1 :::: [[ 0.04731239 -0.75597495]]
###output######## [[0.95268761 0.75597495]]
**********************
iteration: 2 :::: [[ 0.04729963 -0.75129891]]
###output######## [[0.95270037 0.75129891]]
**********************
iteration: 3 :::: [[ 0.04728667 -0.74653278]]
###output######## [[0.95271333 0.74653278]]
**********************
iteration: 4 :::: [[ 0.04727351 -0.74167711]]
###output######## [[0.95272649 0.74167711]]
**********************
iteration: 5 :::: [[ 0.04726014 -0.73673267]]
###output######## [[0.95273986 0.73673267]]
**********************
iteration: 6 :::: [[ 0.04724655 -0.73170042]]
###output######## [[0.95275345 0.73170042]]
**********************
iteration: 7 :::: [[ 0.04723273 -0.7265816 ]]
###output######## [[0.95276727 0.7265816 ]]
**********************
iteration: 8 :::: [[ 0.04721868 -0.72137763]]
###output######## [[0.95278